### ISSUE TITLE
textcleaner.py

### ISSUE THREAD

**Issue by xposix** [greggwilliams58/WordFrequencyCount#4]
https://github.com/greggwilliams58/WordFrequencyCount/blob/f648c1668ade046e6d08ee6acd7bb128966f5d7c/WordFrequencyCount/textcleaner.py#L1

> textcleaner.py
> 1) yikes! this is fugly!
 
I couldn't guess what this code does. I usually add this beside every function:
def gettext(fieldlist, tablename, search_term):
    # This function does bla bla bla bla bla, etc
    # Parameters:
    # - fieldlist: is a list that contains fields to search for in the query XXXXXX
    # - tablename: is the name of the table to extract this fields from 
    # - search_term: etc etc etc etc 
    # Returns:
    # - it returns a list containing XXXXXXXX
    extract = list()

**Comment by greggwilliams58** [comment]
I've done as you suggested and added blocktext.
